### PR TITLE
added option to generate 3d transforms, updated test and readme

### PR DESCRIPTION
**Pull request by magicspon**

### CODE REVIEW

**Comment by benface** [comment]
Thank you for the PR!

I'm not sure I like the commas logic... it is confusing IMO because there are some CSS properties that accept multiple values separated by commas, whereas here it means something else entirely. But more than that, I'm not sure I like the idea of reusing the `translate` option for two different transform functions. I think a more explicit `translate3d` option would be clearer. Ideally the user shouldn't have to read the documentation to know how the plugin works, you know?

Also, I think if we want to add 3D transforms to this plugin, we should add all of the 1-axis transform functions before adding multiple-axis transforms:
- `translateZ`
- `scaleZ` (is it any different from `scale`?)
- `rotateX`
- `rotateY`
- `rotateZ` (is it any different from `rotate`?)

I think we can add all of the above without adding any option, for instance by generating `translateZ` utilities for all the `translate` values, `rotateX` and `rotateY` utilities for all the `rotate` values, etc. We already do it for the 2D `translate` and `scale` functions. Or perhaps we could have a new `3dtransforms` boolean option that controls whether the above are generated or not (in an effort to constrain the filesize if someone is sure not to use 3D transforms and doesn't use PurgeCSS)?

Other useful 3D transform utilities would be `transform-style`, `perspective`, `perspective-origin`, and `backface-visibility`.

What do you think?

**Comment by benface** [comment]
I've been thinking about this some more, and I think a new `3d` option is the right approach. I created an issue here: #5 

Once that's done then we can tackle more complex transforms like this PR does with `translate3d()`.

**Comment by benface** [comment]
@magicspon That said, I changed my mind about the commas logic; I think it's a pretty good idea since commas are never accepted in a `translate()` anyway. It would be better if only two values generated `translate([value-1], [value-2])` instead of `translate3d([value-1], [value-2], 0)`, though. And the same logic should be applied to `scale`.

**Comment by benface** [comment]
Closing to prefer issue #6. Thank you for the PR though, appreciate it!

**Comment by magicspon** [comment]
@benface heyo. sorry about the radio silence, been mega busy with work. Issue #6 sounds good to be.  Nice one.

**Pull request closed without merging**
